services:
  # Nosso banco de dados PostgreSQL
  db:
    image: postgres:latest # Corrigido: a imagem deve estar na mesma linha ou indentada abaixo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin

  # Interface de gerenciamento do banco
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080" # Nota: A porta padrão interna do Adminer é 8080